### PR TITLE
Fix docker usage, and enable telemetry

### PR DESCRIPTION
**Pull request by chcosta**
Applies similar changes as were made in [CliCommandLineParser](https://github.com/dotnet/CliCommandLineParser/commit/027fd6d46bb63e334cc2bf3063936cec8882c0a4).

The most important thing here is that the variables get flowed from .vsts-ci.yml so that the docker container will be properly specified.

### CODE REVIEW

**Comment by chcosta** [comment]
FYI @livarcocc , it looks like the Linux VSTS builds in this repo are failing but claiming success.

```
2018-08-20T17:42:11.4631153Z dotnet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)
2018-08-20T17:42:11.4652438Z Failed to build /_work/10/s/build/Toolset.proj
```

**Comment by chcosta** [comment]
Maybe need a different docker image?

**Comment by livarcocc** [comment]
@chcosta that's very strange, given that we are using the same docker image in all runs and this seems to be a dotnet dependency.

**Comment by livarcocc** [comment]
@chcosta also, why isn't it being marked as failure?

**Comment by chcosta** [comment]
Yep, that was my primary question.  I've enabled diag logging on the build.  i'm going to close / re-open this PR to try to get another run with more info.

**Comment by chcosta** [comment]
hmm... well now it succeeded :(  I'll try to force a failure in this branch.

**Comment by chcosta** [comment]
I made an update to the build.sh script so that exit code status is properly reported from the script and now VSTS is actually showing failures when there is a problem installing the toolset.  I'm still trying to understand why we're occasionally seeing the `dotnet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by dotnet)` failure.

**Comment by chcosta** [comment]
It appears that the failures occurred consistently on two of the Linux agents, but runs are fine on the remaining agents.  I've disabled the two problematic machines and filed a ticket to have them reimaged.

**Comment by livarcocc** [comment]
@chcosta thanks for looking into this and for the changes. I will port the script changes back to the parser as well and will incorporate it in the other repos I bring online on YAML and VSTS.

**Pull request merged**
