### PR TITLE
Fix redirected progress output to be less verbose.

### PR DESCRIPTION
**Pull request by peterhuene**
Currently, when the progress output is redirected, it prints out a lot of
percentages and is very verbose.

This commit changes the redirected output to print a period for each 10 percent
that completes, resulting in much less output but still showing progress.

Fixes dotnet/cli#8288.

### CODE REVIEW

**Comment by peterhuene** [comment]
@livarcocc how do we roll a new build of this to include the fix in CLI?

**Comment by livarcocc** [comment]
Look at VSO for the build for this merge and update DependencyVersions in the CLI with said build.

**Comment by peterhuene** [comment]
So that I'm on the same page:

1. Bump version number in https://github.com/dotnet/dotnet-cli-archiver/blob/master/build/Versions.props
2. Kick off VSTS build which publishes new package.
3. Update CLI dependency to match new version number.

Is that correct?

**Comment by livarcocc** [comment]
You shouldn't have to do 1 or 2. Just merging the PR should have kicked a build.

Pick it up here: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?definitionId=5619&_a=completed and update the CLI.

**Comment by peterhuene** [comment]
Isn't that for the parser and not the archiver?

**Comment by livarcocc** [comment]
sorry, handling a fire now and doing too many things at once. I guess you just need to kick off a build on the archiver. Not sure why there is no trigger. ping @tannergooding to confirm and see why there is no trigger.

**Comment by peterhuene** [comment]
Will do, thanks!

**Pull request merged**
